# Optional Name for code
name: Azure Static Web Apps CI/CD

# Signals when to start the pipeline - when the master branch has commits
trigger:
  branches:
    include:
      - master

# What virtual machine that this pipeline will run on - on Azure DevOps, this .yml file will run on a ubuntu VM
# To run this pipeline.
pool:
  vmImage: ubuntu-latest

# Checkouts from the git repo, signals to the pipeline to checkout from the repo the pipeline is in
# Submodules refers to sub repositories in the Git repo, which doesn't exist for this project, so it is
# unnecessary
steps:
  - checkout: self
    submodules: true

# Installs the latest version of Node.js on the VM, a runtime enviornment that runs can run on most operating systems
  - script: |
      curl -sL https://deb.nodesource.com/setup_21.x | sudo -E bash -
      sudo apt-get install -y nodejs
      sudo npm install -g npm@latest
    displayName: 'Install Node.js'

# Installs npm, a package manager that manages Node.js
  - script: npm install
    displayName: 'npm install'
    workingDirectory: .

# Builds program as specified in the package.json file
  - script: npm run build
    displayName: 'npm build'
    workingDirectory: .

# Sets up the Static Web App(SWA) for the code to be deployed to.
# Inputs refers to what Azure needs to deploy the web page
  # the api token is the special token needed to authenticate the code.
    # Note: It is extremely bad practice and extremely insecure to have thi code in a repo
    # It is best practice to put it in a (enviornment?) variable for use in Azure DevOps
  # app location is where the code for the SWA is, which includes an HTML & CSS file, and some images
  # api: No apis used.
  # output location: Where the built app content is to be stored after the build process
  # copy_settings: unnecessary i believe for this pipeline.
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: '2bb9865beac9487bbdc4a7fc22b6020db6cdc93e588b2ea29b683390be96ae455-34bf1746-6073-4326-8a58-ed5a9d1618b401e165869'
      skip_app_build: 'true'
      app_location: "deployment-package" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "deployment-package" # Built app content directory - optional
      copy_settings: |
        {
          "source": "images",
          "destination": "images"
        }
